spring.jackson.deserialization.fail-on-unknown-properties=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

paytrack.demo-shell-registration-number=198601234501

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=${DB_URL:jdbc:mysql://localhost/paytrack_db?serverTimezone=Asia/Kuala_Lumpur&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.hibernate.SQL=debug

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
info.app.name=PayTrack
info.app.version=1.0

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
